### ISSUE TITLE
Name Field must be between 6 and 100 characters

### ISSUE THREAD

**Issue by bzekePerka** [rwsmith/ImageSite#1]
The name field throws an error if you give less than 6 characters. We should probably lower this down to 2-4 and maybe have some dialog box appear that tells you such.

**Comment by chouze** [comment]
Lowered on server, no dialog as of yet

**Comment by bzekePerka** [comment]
Done commit 65697d49ecbfcb7cb7a4ad7a0b2f6c2fb6cbd9a5
