### ISSUE TITLE
Delete button for photos

### ISSUE THREAD

**Issue by chouze** [rwsmith/ImageSite#10]
Add a button to delete a photo on the photo page (make sure admins can see it too)

**Comment by rwsmith** [comment]
Should this wipe out everything we know about the photo (e.g. delete the rows from photo, comments, etc)

**Comment by chouze** [comment]
Yes. We already have a picture/delete endpoint that should work as is, just needs to be hooked up to the page

**Comment by rwsmith** [comment]
Closed by https://github.com/rwsmith/ImageSite/commit/7aae3f9de119ba86af2ffe884fa2695dc5a0030b
