### ISSUE TITLE
Make email notifications work

### ISSUE THREAD

**Issue by chouze** [rwsmith/ImageSite#11]
When a person gets tagged in a photo, send an email to them (stubbed out)

**Comment by rwsmith** [comment]
Closed by https://github.com/rwsmith/ImageSite/commit/967a406a681dad257156be500531e42bf40e9f69

**Comment by rwsmith** [comment]
If I have time, would be nice to integrate with this https://github.com/Sandglaz/bootstrap-tagautocomplete
