### ISSUE TITLE
Pull comments from server after posting

### ISSUE THREAD

**Issue by chouze** [rwsmith/ImageSite#12]
Instead of grabbing the text from the comment box, send everything to the server and only display the text the server sends back. 
For example, post this in a comment: 
&lt;button type=&quot;button&quot;&gt;Uh Oh&lt;/button&gt; <- This will be a button for the user who posted it, until they refresh the page

**Comment by rwsmith** [comment]
Closed by https://github.com/rwsmith/ImageSite/commit/6de886a6e272a3345beb7ab631bd4807851889b2
