### ISSUE TITLE
Minimum Comment Character Count is Wrong

### ISSUE THREAD

**Issue by bzekePerka** [rwsmith/ImageSite#7]
Says it should be at least 5, I typed "First" and it wouldn't submit. Also might be a good time to mention that we can just limit it to at least one character (trimmed first)?

**Comment by chouze** [comment]
Which field?

**Comment by bzekePerka** [comment]
When I tried to comment on a photo. I imagine it's just one field, right?

**Comment by chouze** [comment]
This looks like it's done via Javascript not on the backend

**Comment by rwsmith** [comment]
Closed by https://github.com/rwsmith/ImageSite/commit/309e491f48c37de99cfac44542fb997dc7ebfa78
