### ISSUE TITLE
Add sign in button to top bar

### ISSUE THREAD

**Issue by chouze** [rwsmith/ImageSite#8]
Currently, if I am viewing an image, such as http://elvis.rowan.edu/~smithr1/ImageSite/application.cgi/picture/9ed8d26f-1bb5-4f2d-bdc4-b89ca18752e0.jpg and not signed in. Only a sign up button appears, and I have to go to the main page to find the sign in screen. We should add a sign in button next to the sign up button

**Comment by bzekePerka** [comment]
Done commit 65da6ce5cf060723c3927de876224e6346deb3c6
